#!/usr/bin/env python
"""Where along the refusal opening does the adapter's refusal circuit commit?

Session "[refusal-token-tracing]" (fd1f0d19), 2026-08-12.

Offline analysis of the 30 first-ten-token base-vs-adapter overlays (tc8192_refusal_first10). For each
graph (prompt x refusal-position) it ranks the adapter graph's feature nodes
by their influence on the traced refusal-token logit, classifies the CONTEXT TOKEN each fires on
(harmful-request word vs. assistant-turn structure vs. an already-emitted refusal token), measures how much
of the target's feature influence is adapter- vs base- vs shared-sourced, and tracks which specific adapter
features (layer, feature-id) RECUR across positions and across prompts. This localises where the refusal
decision is driven from the adapter rather than the shared base circuitry.

Writes graph_analysis.md + adapter_influence_by_pos.pdf next to this script (all under my_notes/08-10-26/).
No GPU, no HF download: reads only the overlay JSONs on scratch.
"""
from __future__ import annotations
import json, glob, re
from collections import defaultdict, Counter
from pathlib import Path

BD = Path("/nlp/scr/siddharth/transcoder-adapters/base_adapter_comparisons/tc8192_refusal_first10")
OUT = Path(__file__).resolve().parent
PROMPTS = ["harm_125", "harm_139", "harm_116"]
NAMES = {"harm_125": "meth", "harm_139": "DDoS", "harm_116": "pipe bomb"}
# Which prompt-token ctx indices are the harmful REQUEST content (between the user header and the
# end-of-turn), per prompt pos00 token layout; computed generically below from prompt_tokens instead.


def classify_ctx(tok: str, ctx: int, n_prompt: int, req_lo: int, req_hi: int) -> str:
    """Bucket the context token a feature fires on."""
    if ctx >= req_hi:  # inside/after the model turn -> assistant tokens (turn structure or emitted refusal)
        return "assistant/refusal"
    if req_lo <= ctx < req_hi:
        return "harmful-request"
    return "turn-structure"


def load_graph(f: str) -> dict:
    """Analyse the ADAPTER graph directly: every transcoder feature attributes toward the SAME refusal
    token (unlike the overlay, where base nodes attribute toward the base model's echo target -- mixing
    those would be apples-to-oranges), so ranking all adapter features by |influence| is meaningful."""
    d = json.load(open(f))
    toks = d["metadata"]["prompt_tokens"]
    n = len(toks)
    try:
        eot = next(i for i, t in enumerate(toks) if t == "<end_of_turn>")
    except StopIteration:
        eot = n
    req_lo, req_hi = 4, eot
    tgt = max((x for x in d["nodes"] if x.get("is_target_logit")), key=lambda x: x.get("token_prob", 0), default=None)
    adap = [x for x in d["nodes"] if x.get("feature_type") == "cross layer transcoder"]
    for x in adap:
        c = x["ctx_idx"]
        x["_ctxtok"] = toks[c] if 0 <= c < n else "?"
        x["_bucket"] = classify_ctx(x["_ctxtok"], c, n, req_lo, req_hi)
        # layer-local feature index from node_id "{layer}_{featidx}_{ctx}" (matches the viewer's L?/F? label)
        m = re.match(r"(\d+)_(\d+)_", str(x.get("node_id", "")))
        x["source_feature_id"] = int(m.group(2)) if m else x.get("feature")
        # per-node influence share of |influence| by bucket, for the position summary
        x["_absinfl"] = abs(x.get("influence", 0.0))
    adap.sort(key=lambda x: -abs(x.get("influence", 0.0)))
    return {"toks": toks, "n": n, "req_lo": req_lo, "req_hi": req_hi, "target": tgt,
            "adap": adap, "infl_by_src": {}, "n_feat": len(adap)}


def main():
    # graph[prompt][pos] = loaded
    G = defaultdict(dict)
    for pid in PROMPTS:
        for f in sorted(glob.glob(str(BD / f"adapter/*{pid}__pos*.json"))):
            pos = int(re.search(r"pos(\d+)", f).group(1))
            G[pid][pos] = load_graph(f)

    lines = ["<!-- [refusal-token-tracing] (session fd1f0d19), 2026-08-12. Generated by analyze_first10_graphs.py -->",
             "# Where along the refusal opening does the adapter's circuit commit?", "",
             "Offline structural analysis of the 30 `tc8192_refusal_first10` **adapter** attribution graphs "
             "(3 prompts x 10 positions). We analyse the adapter graph directly (not the overlay): within it, "
             "every transcoder feature attributes toward the SAME refusal token, so ranking features by "
             "|influence| is meaningful (in the overlay, base nodes attribute toward the base model's echo/"
             "gibberish target, so an adapter-vs-base influence share would be apples-to-oranges). "
             "For each traced refusal token we ask (a) which adapter features most influence it, (b) what context "
             "token each fires on -- the harmful request, the assistant-turn structure, or an already-emitted "
             "refusal token, and (c) which adapter features recur across positions/prompts. Feature ids match the "
             "viewer's `L?/F?` labels; to see what a feature detects, open it in the viewer (port 8054) for its "
             "top tokens + activating examples (§3-§4 list the top recurring ones to inspect).", "",
             "## Findings (narrative)", "",
             "**The refusal opening is driven mostly by turn-position features, not by reading the harmful "
             "request.** At almost every one of the 30 (prompt x position) graphs, the highest-influence adapter "
             "features toward the refusal token fire on the chat *scaffolding* -- `<start_of_turn>`, `user`, "
             "`model`, `\\n` -- i.e. \"I am the assistant, at the start of a reply to a user turn.\" The share of "
             "the top-8 features' influence that instead reads the harmful *request* content (e.g. the token "
             "\"methamphetamine\") is mostly 0-13% (Table 1, `req%`; figure left panel). So the circuit that emits "
             "\"I cannot...\" is largely a position/format-triggered response circuit, with harmful-content "
             "detection playing a smaller, prompt-specific role.", "",
             "**The one clear content trigger is \"bomb\".** The pipe-bomb prompt (harm_116) is the exception: a "
             "layer-0 feature firing on the token \" bomb\" is a *top* feature at several positions (pos2 "
             "L0/F3059, pos6 L0/F3497) and request-reading reaches ~25% of top-8 influence at pos1 -- far more "
             "than \"methamphetamine\" (harm_125, intermittent) or \"script\" (harm_139, almost never). This "
             "matches the huge-adapter split, where weapons/CBRN are the most reliably refused categories.", "",
             "**The refusal is already committed at position 0 (\"I\").** There is no position where a "
             "harmful-content feature suddenly switches the refusal on: the same turn-position features that drive "
             "\"I\" (pos0) drive \"cannot\", \"provide\", and the rest of the opening. A prompt-general set of "
             "adapter features recurs across all three prompts and almost all positions (Table 4: L0/F5489, "
             "L5/F6977, L6/F7928, L8/F3284, L9/F427, L12/F5446, ...), and these are exactly the scaffolding "
             "features. This is consistent with the prefill-flip result (instruct refuses at k=0, no \"I\" needed) "
             "and the huge-adapter split (the opener token is a *readout* of an already-made decision).", "",
             "**Caveat -- these are labelled only by firing context, not verified as refusal-specific.** A feature "
             "firing on `<start_of_turn>` could be a generic response-start feature active for compliant answers "
             "too; distinguishing \"refusal circuit\" from \"generic assistant-response circuit\" requires "
             "contrasting against a COMPLIANCE graph (same feature active or not when the adapter complies). The "
             "huge-adapter compliance prompts (huge_adapter_refusal_split.md) are the natural contrast set. "
             "**One-sentence version:** across the first ten refusal tokens the adapter's refusal opening is driven "
             "overwhelmingly by chat-turn-position features (active from \"I\" onward, shared across prompts), with "
             "genuine harmful-content reading minor and prompt-specific (strongest for \"bomb\") -- so the refusal "
             "commits at the very first token as a position-triggered response, pending a compliance-graph contrast "
             "to confirm the features are refusal-specific.", ""]

    # ---- Table 1: top adapter feature + bucket influence-share per position ----
    lines += ["## 1. Top adapter feature and where the refusal-token influence comes from, per position", "",
              "`#feat` = adapter feature nodes in the graph. `top feat` = highest-|influence| feature (layer/feat "
              "@ the context token it fires on). `request/asst/struct %` = share of the top-8 features' |influence| "
              "coming from features firing on harmful-request / assistant-refusal / turn-structure tokens.", ""]
    for pid in PROMPTS:
        lines += [f"### {pid} ({NAMES[pid]})", "",
                  "| pos | target tok | #feat | top feat @ ctx-token | bucket | req% | asst% | struct% |",
                  "|---:|---|---:|---|---|---:|---:|---:|"]
        for pos in sorted(G[pid]):
            g = G[pid][pos]
            tgt = g["target"]
            ttok = tgt["clerp"].replace("Output ", "").split(" (p")[0] if tgt else "?"
            top = g["adap"][0] if g["adap"] else None
            topstr = f"L{top['layer']}/F{top['source_feature_id']} @ {top['_ctxtok']!r}" if top else "—"
            bucket = top["_bucket"] if top else "—"
            top8 = g["adap"][:8]; tot = sum(x["_absinfl"] for x in top8) or 1
            share = defaultdict(float)
            for x in top8:
                share[x["_bucket"]] += x["_absinfl"]
            req = 100 * share["harmful-request"] / tot
            asst = 100 * share["assistant/refusal"] / tot
            struct = 100 * share["turn-structure"] / tot
            lines.append(f"| {pos} | {ttok} | {len(g['adap'])} | {topstr} | {bucket} | {req:.0f}% | {asst:.0f}% | {struct:.0f}% |")
        lines.append("")

    # ---- Table 2: does a top-5 adapter feature fire on the harmful request? ----
    lines += ["## 2. Do influential adapter features read the harmful request?", "",
              "For each position, the context-token bucket of the top-5 adapter features (by |influence|). "
              "`harmful-request` firing means the adapter feature is reading the request content (e.g. "
              "'methamphetamine') to drive the refusal token; `assistant/refusal` means it fires on the "
              "turn structure or the already-emitted refusal words.", ""]
    for pid in PROMPTS:
        lines += [f"### {pid} ({NAMES[pid]})", "",
                  "| pos | top-5 adapter-feature buckets | harmful-request ctx tokens hit |",
                  "|---:|---|---|"]
        for pos in sorted(G[pid]):
            g = G[pid][pos]
            top5 = g["adap"][:5]
            buckets = Counter(x["_bucket"] for x in top5)
            bstr = ", ".join(f"{k}:{v}" for k, v in buckets.most_common())
            hits = sorted({x["_ctxtok"].strip() for x in top5 if x["_bucket"] == "harmful-request"})
            lines.append(f"| {pos} | {bstr} | {', '.join(hits) if hits else '—'} |")
        lines.append("")

    # ---- Table 3: recurrence across positions (per prompt) ----
    lines += ["## 3. Adapter features that recur across positions (candidate persistent refusal circuit)", "",
              "Adapter features (layer/feat) appearing in the **top-8 by |influence|** at >=4 of the 10 positions "
              "of a prompt. A feature that drives the refusal token at many positions is a persistent part of the "
              "refusal circuit rather than a one-off.", ""]
    for pid in PROMPTS:
        cnt = Counter()
        ctxrec = defaultdict(list)
        for pos in sorted(G[pid]):
            for x in G[pid][pos]["adap"][:8]:
                key = (int(x["layer"]), x.get("source_feature_id"))
                cnt[key] += 1
                ctxrec[key].append(x["_bucket"])
        rec = [(k, c) for k, c in cnt.items() if c >= 4]
        rec.sort(key=lambda kc: -kc[1])
        lines += [f"### {pid} ({NAMES[pid]})", ""]
        if rec:
            lines += ["| adapter feat | # of 10 positions | usual bucket |", "|---|---:|---|"]
            for (layer, fid), c in rec:
                b = Counter(ctxrec[(layer, fid)]).most_common(1)[0][0]
                lines.append(f"| L{layer}/F{fid} | {c} | {b} |")
        else:
            lines.append("_No adapter feature reached the top-8 at >=4 positions (circuit is position-specific)._")
        lines.append("")

    # ---- Table 4: adapter features shared ACROSS prompts ----
    lines += ["## 4. Adapter features shared across all three prompts (prompt-general refusal features)", "",
              "Adapter features that appear in the top-8 of at least one position in **every** prompt — candidates "
              "for a prompt-general (topic-independent) refusal circuit, as opposed to topic-specific features.", ""]
    perprompt = {}
    for pid in PROMPTS:
        s = set()
        for pos in G[pid]:
            for x in G[pid][pos]["adap"][:8]:
                s.add((int(x["layer"]), x.get("source_feature_id")))
        perprompt[pid] = s
    shared = set.intersection(*perprompt.values())
    if shared:
        lines += ["| adapter feat |", "|---|"] + [f"| L{l}/F{f} |" for l, f in sorted(shared)]
    else:
        lines.append("_No adapter feature is top-8 in all three prompts — the high-influence adapter features are "
                     "largely topic/prompt-specific at this budget._")
    lines.append("")

    (OUT / "graph_analysis.md").write_text("\n".join(lines) + "\n")
    print("wrote", OUT / "graph_analysis.md")

    # ---- Figure: share of top-8 influence that reads the harmful request, and count of top-5 doing so ----
    import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
    col = {"harm_125": "#c53030", "harm_139": "#2b6cb0", "harm_116": "#2f855a"}
    for pid in PROMPTS:
        poss = sorted(G[pid])
        reqshare = []
        harmhits = []
        for pos in poss:
            g = G[pid][pos]
            top8 = g["adap"][:8]; tot = sum(x["_absinfl"] for x in top8) or 1
            reqshare.append(100 * sum(x["_absinfl"] for x in top8 if x["_bucket"] == "harmful-request") / tot)
            harmhits.append(sum(1 for x in g["adap"][:5] if x["_bucket"] == "harmful-request"))
        ax1.plot(poss, reqshare, marker="o", color=col[pid], label=f"{pid} ({NAMES[pid]})")
        ax2.plot(poss, harmhits, marker="s", color=col[pid], label=f"{pid} ({NAMES[pid]})")
    ax1.set_title("Share of top-8 adapter-feature influence\nthat reads the harmful request"); ax1.set_ylabel("% of top-8 |influence| on request tokens")
    ax2.set_title("How many of the top-5 adapter features\nread the harmful request"); ax2.set_ylabel("# of top-5 firing on request tokens")
    for ax in (ax1, ax2):
        ax.set_xlabel("refusal-token position (0=I, 1=cannot, ...)"); ax.set_xticks(range(10)); ax.grid(alpha=.3); ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "adapter_influence_by_pos.pdf"); fig.savefig(OUT / "adapter_influence_by_pos.png", dpi=150)
    print("wrote", OUT / "adapter_influence_by_pos.pdf")


if __name__ == "__main__":
    main()
