#!/usr/bin/env python
"""Where along the refusal opening does the adapter's refusal circuit commit?

Session "[refusal-token-tracing]" (fd1f0d19), 2026-08-12.

Offline analysis of the 30 first-ten-token base-vs-adapter overlays (tc8192_refusal_first10). For each
graph (prompt x refusal-position) it ranks the ADAPTER-specific feature nodes (node_shape='adapter_model')
by their influence on the traced refusal-token logit, classifies the CONTEXT TOKEN each fires on
(harmful-request word vs. assistant-turn structure vs. an already-emitted refusal token), measures how much
of the target's feature influence is adapter- vs base- vs shared-sourced, and tracks which specific adapter
features (layer, feature-id) RECUR across positions and across prompts. This localises where the refusal
decision is driven from the adapter rather than the shared base circuitry.

Writes graph_analysis.md + adapter_influence_by_pos.pdf next to this script (all under my_notes/08-10-26/).
No GPU, no HF download: reads only the overlay JSONs on scratch.
"""
from __future__ import annotations
import json, glob, re
from collections import defaultdict, Counter
from pathlib import Path

BD = Path("/nlp/scr/siddharth/transcoder-adapters/base_adapter_comparisons/tc8192_refusal_first10")
OUT = Path(__file__).resolve().parent
PROMPTS = ["harm_125", "harm_139", "harm_116"]
NAMES = {"harm_125": "meth", "harm_139": "DDoS", "harm_116": "pipe bomb"}
# Which prompt-token ctx indices are the harmful REQUEST content (between the user header and the
# end-of-turn), per prompt pos00 token layout; computed generically below from prompt_tokens instead.


def classify_ctx(tok: str, ctx: int, n_prompt: int, req_lo: int, req_hi: int) -> str:
    """Bucket the context token a feature fires on."""
    if ctx >= req_hi:  # inside/after the model turn -> assistant tokens (turn structure or emitted refusal)
        return "assistant/refusal"
    if req_lo <= ctx < req_hi:
        return "harmful-request"
    return "turn-structure"


def load_graph(f: str) -> dict:
    d = json.load(open(f))
    toks = d["metadata"]["prompt_tokens"]
    n = len(toks)
    # request span = between 'user\n' (ctx 3) and the first <end_of_turn>
    try:
        eot = next(i for i, t in enumerate(toks) if t == "<end_of_turn>")
    except StopIteration:
        eot = n
    req_lo, req_hi = 4, eot
    tgt = max((x for x in d["nodes"] if x.get("is_target_logit")), key=lambda x: x.get("token_prob", 0), default=None)
    feats = [x for x in d["nodes"] if x.get("feature_type") == "cross layer transcoder"]
    # influence sums by source
    infl_by_src = defaultdict(float)
    for x in feats:
        infl_by_src[x.get("node_shape")] += abs(x.get("influence", 0.0))
    adap = [x for x in feats if x.get("node_shape") == "adapter_model"]
    for x in adap:
        c = x["ctx_idx"]
        x["_ctxtok"] = toks[c] if 0 <= c < n else "?"
        x["_bucket"] = classify_ctx(x["_ctxtok"], c, n, req_lo, req_hi)
    adap.sort(key=lambda x: -abs(x.get("influence", 0.0)))
    return {"toks": toks, "n": n, "req_lo": req_lo, "req_hi": req_hi, "target": tgt,
            "adap": adap, "infl_by_src": infl_by_src, "n_feat": len(feats)}


def main():
    # graph[prompt][pos] = loaded
    G = defaultdict(dict)
    for pid in PROMPTS:
        for f in sorted(glob.glob(str(BD / f"overlay/*{pid}__pos*.json"))):
            pos = int(re.search(r"pos(\d+)", f).group(1))
            G[pid][pos] = load_graph(f)

    lines = ["<!-- [refusal-token-tracing] (session fd1f0d19), 2026-08-12. Generated by analyze_first10_graphs.py -->",
             "# Where along the refusal opening does the adapter's circuit commit?", "",
             "Offline structural analysis of the 30 `tc8192_refusal_first10` overlays (3 prompts x 10 positions). "
             "For each traced refusal token we rank the **adapter-specific** feature nodes "
             "(`node_shape=adapter_model`) by |influence| on that token's logit, and ask (a) how much of the "
             "target's feature influence is adapter- vs base- vs shared-sourced, (b) what context token each top "
             "adapter feature fires on (the harmful request, the assistant-turn structure, or an already-emitted "
             "refusal token), and (c) which adapter features recur across positions/prompts. "
             "Base side is chat-template gibberish (expected), so this reads the adapter side only.", ""]

    # ---- Table 1: adapter share of influence + top adapter feature per position ----
    lines += ["## 1. Adapter vs base influence, and the top adapter feature, per position", "",
              "`adap%` = adapter-sourced share of total transcoder-feature |influence| (base+adapter+shared). "
              "`#adap` = number of adapter feature nodes. `top adapter feat` = highest-|influence| adapter feature "
              "(layer/feat @ context token it fires on).", ""]
    for pid in PROMPTS:
        lines += [f"### {pid} ({NAMES[pid]})", "",
                  "| pos | target tok | adap% | #adap | top adapter feat @ ctx-token | its bucket |",
                  "|---:|---|---:|---:|---|---|"]
        for pos in sorted(G[pid]):
            g = G[pid][pos]
            tgt = g["target"]
            ttok = tgt["clerp"].replace("Output ", "").split(" (p")[0] if tgt else "?"
            s = g["infl_by_src"]; tot = sum(s.values()) or 1
            adappct = 100 * s.get("adapter_model", 0) / tot
            top = g["adap"][0] if g["adap"] else None
            topstr = f"L{top['layer']}/F{top.get('source_feature_id')} @ {top['_ctxtok']!r}" if top else "—"
            bucket = top["_bucket"] if top else "—"
            lines.append(f"| {pos} | {ttok} | {adappct:.0f}% | {len(g['adap'])} | {topstr} | {bucket} |")
        lines.append("")

    # ---- Table 2: does a top-5 adapter feature fire on the harmful request? ----
    lines += ["## 2. Do influential adapter features read the harmful request?", "",
              "For each position, the context-token bucket of the top-5 adapter features (by |influence|). "
              "`harmful-request` firing means the adapter feature is reading the request content (e.g. "
              "'methamphetamine') to drive the refusal token; `assistant/refusal` means it fires on the "
              "turn structure or the already-emitted refusal words.", ""]
    for pid in PROMPTS:
        lines += [f"### {pid} ({NAMES[pid]})", "",
                  "| pos | top-5 adapter-feature buckets | harmful-request ctx tokens hit |",
                  "|---:|---|---|"]
        for pos in sorted(G[pid]):
            g = G[pid][pos]
            top5 = g["adap"][:5]
            buckets = Counter(x["_bucket"] for x in top5)
            bstr = ", ".join(f"{k}:{v}" for k, v in buckets.most_common())
            hits = sorted({x["_ctxtok"].strip() for x in top5 if x["_bucket"] == "harmful-request"})
            lines.append(f"| {pos} | {bstr} | {', '.join(hits) if hits else '—'} |")
        lines.append("")

    # ---- Table 3: recurrence across positions (per prompt) ----
    lines += ["## 3. Adapter features that recur across positions (candidate persistent refusal circuit)", "",
              "Adapter features (layer/feat) appearing in the **top-8 by |influence|** at >=4 of the 10 positions "
              "of a prompt. A feature that drives the refusal token at many positions is a persistent part of the "
              "refusal circuit rather than a one-off.", ""]
    for pid in PROMPTS:
        cnt = Counter()
        ctxrec = defaultdict(list)
        for pos in sorted(G[pid]):
            for x in G[pid][pos]["adap"][:8]:
                key = (int(x["layer"]), x.get("source_feature_id"))
                cnt[key] += 1
                ctxrec[key].append(x["_bucket"])
        rec = [(k, c) for k, c in cnt.items() if c >= 4]
        rec.sort(key=lambda kc: -kc[1])
        lines += [f"### {pid} ({NAMES[pid]})", ""]
        if rec:
            lines += ["| adapter feat | # of 10 positions | usual bucket |", "|---|---:|---|"]
            for (layer, fid), c in rec:
                b = Counter(ctxrec[(layer, fid)]).most_common(1)[0][0]
                lines.append(f"| L{layer}/F{fid} | {c} | {b} |")
        else:
            lines.append("_No adapter feature reached the top-8 at >=4 positions (circuit is position-specific)._")
        lines.append("")

    # ---- Table 4: adapter features shared ACROSS prompts ----
    lines += ["## 4. Adapter features shared across all three prompts (prompt-general refusal features)", "",
              "Adapter features that appear in the top-8 of at least one position in **every** prompt — candidates "
              "for a prompt-general (topic-independent) refusal circuit, as opposed to topic-specific features.", ""]
    perprompt = {}
    for pid in PROMPTS:
        s = set()
        for pos in G[pid]:
            for x in G[pid][pos]["adap"][:8]:
                s.add((int(x["layer"]), x.get("source_feature_id")))
        perprompt[pid] = s
    shared = set.intersection(*perprompt.values())
    if shared:
        lines += ["| adapter feat |", "|---|"] + [f"| L{l}/F{f} |" for l, f in sorted(shared)]
    else:
        lines.append("_No adapter feature is top-8 in all three prompts — the high-influence adapter features are "
                     "largely topic/prompt-specific at this budget._")
    lines.append("")

    (OUT / "graph_analysis.md").write_text("\n".join(lines) + "\n")
    print("wrote", OUT / "graph_analysis.md")

    # ---- Figure: adapter% of influence vs position, one line per prompt ----
    import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
    col = {"harm_125": "#c53030", "harm_139": "#2b6cb0", "harm_116": "#2f855a"}
    for pid in PROMPTS:
        poss = sorted(G[pid])
        adappct = []
        harmhits = []
        for pos in poss:
            g = G[pid][pos]; s = g["infl_by_src"]; tot = sum(s.values()) or 1
            adappct.append(100 * s.get("adapter_model", 0) / tot)
            harmhits.append(sum(1 for x in g["adap"][:5] if x["_bucket"] == "harmful-request"))
        ax1.plot(poss, adappct, marker="o", color=col[pid], label=f"{pid} ({NAMES[pid]})")
        ax2.plot(poss, harmhits, marker="s", color=col[pid], label=f"{pid} ({NAMES[pid]})")
    ax1.set_title("Adapter share of transcoder-feature influence\non the refusal token"); ax1.set_ylabel("adapter % of |influence|")
    ax2.set_title("How many of the top-5 adapter features\nread the harmful request"); ax2.set_ylabel("# of top-5 firing on request tokens")
    for ax in (ax1, ax2):
        ax.set_xlabel("refusal-token position (0=I, 1=cannot, ...)"); ax.set_xticks(range(10)); ax.grid(alpha=.3); ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "adapter_influence_by_pos.pdf"); fig.savefig(OUT / "adapter_influence_by_pos.png", dpi=150)
    print("wrote", OUT / "adapter_influence_by_pos.pdf")


if __name__ == "__main__":
    main()
