#!/usr/bin/env python
"""Are the refusal-opening adapter features refusal-SPECIFIC, or generic response-start features?

Session "[refusal-token-tracing]" (fd1f0d19), 2026-08-12.

Resolves the caveat of graph_analysis.md: the features that drive the "I cannot..." opening fire on the
chat scaffolding (<start_of_turn>/user/model/\\n). Are they refusal-specific, or do they fire whenever the
adapter starts ANY reply? We answer by contrast: compare the adapter's first-ten-token graphs on prompts
it REFUSES (tc8192_refusal_first10) vs. prompts it COMPLIES with (tc8192_compliance_first10, benign +
kept jailbreaks). For each side we take the "feature vocabulary" = the set of adapter features that reach
the top-8 by |influence| at any position of any prompt. A refusal feature that ALSO appears in the
compliance vocabulary is a generic response-start feature; one that appears ONLY on the refusal side is a
candidate refusal-specific feature.

Reads the two adapter/ graph dirs directly (reusing analyze_first10_graphs.load_graph). Writes
compare_refusal_compliance.md + refusal_vs_compliance_overlap.pdf next to this script (my_notes/08-10-26/).
"""
from __future__ import annotations
import sys, glob, re
from collections import defaultdict, Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from analyze_first10_graphs import load_graph  # noqa: E402

BASE = Path("/nlp/scr/siddharth/transcoder-adapters/base_adapter_comparisons")
REFUSAL_DIR = BASE / "tc8192_refusal_first10" / "adapter"
COMPLY_DIR = BASE / "tc8192_compliance_first10" / "adapter"
TOPK = 8  # a feature is "in the vocabulary" if it reaches the top-8 by |influence| at some position


def feature_vocab(adapter_dir: Path):
    """Return (vocab set of (layer,feat), per-prompt recurring counts, prompt->openings)."""
    per_prompt_pos = defaultdict(dict)  # pid -> pos -> loaded graph
    for f in sorted(glob.glob(str(adapter_dir / "*__pos*.json"))):
        m = re.search(r"/([^/]+?)__pos(\d+)", f)
        pid, pos = m.group(1).split("__")[-1], int(m.group(2))  # strip run-name prefix -> just harm_xxx/benign_xxx
        per_prompt_pos[pid][pos] = load_graph(f)
    vocab = set()
    feat_positions = Counter()  # (layer,feat) -> # of (prompt,pos) graphs where it's top-8
    feat_bucket = defaultdict(Counter)
    for pid, posmap in per_prompt_pos.items():
        for pos, g in posmap.items():
            for x in g["adap"][:TOPK]:
                key = (int(x["layer"]), x["source_feature_id"])
                vocab.add(key); feat_positions[key] += 1; feat_bucket[key][x["_bucket"]] += 1
    return {"vocab": vocab, "counts": feat_positions, "bucket": feat_bucket,
            "prompts": sorted(per_prompt_pos), "n_graphs": sum(len(p) for p in per_prompt_pos.values())}


def main():
    R = feature_vocab(REFUSAL_DIR)
    C = feature_vocab(COMPLY_DIR)
    rvocab, cvocab = R["vocab"], C["vocab"]

    # Refusal features that recur (top-8 at >=6 of the graphs) -- the persistent refusal-opening circuit.
    persistent = sorted([k for k, c in R["counts"].items() if c >= 6], key=lambda k: -R["counts"][k])
    shared_generic = [k for k in persistent if k in cvocab]        # also drive compliant openings -> generic
    refusal_only = [k for k in persistent if k not in cvocab]      # only on the refusal side -> candidate specific

    inter = rvocab & cvocab
    jacc = len(inter) / len(rvocab | cvocab) if (rvocab | cvocab) else 0.0

    def fmt(k):
        l, f = k
        b = R["bucket"][k].most_common(1)[0][0] if k in R["bucket"] else "?"
        return f"L{l}/F{f} ({b})"

    lines = ["<!-- [refusal-token-tracing] (session fd1f0d19), 2026-08-12. Generated by compare_refusal_vs_compliance.py -->",
             "# Are the refusal-opening features refusal-specific, or generic response-start features?", "",
             "Contrast of the adapter's first-ten-token graphs on prompts it **refuses** "
             f"(`tc8192_refusal_first10`, {R['n_graphs']} graphs, prompts {R['prompts']}) vs. prompts it "
             f"**complies** with (`tc8192_compliance_first10`, {C['n_graphs']} graphs, prompts {C['prompts']}). "
             f"A feature is in a side's *vocabulary* if it reaches the top-{TOPK} by |influence| at some position. "
             "A persistent refusal feature that also appears in the compliance vocabulary is a **generic "
             "response-start** feature; one absent from it is a **candidate refusal-specific** feature.", "",
             "## Findings (narrative)", ""]

    if not C["prompts"]:
        lines += ["**No compliant prompts were traced** -- every candidate was refused by tc8192 under the chat "
                  "template (see the compliance run's `prompts/openings.json` `_skipped_refusals`). The benign "
                  "controls should have complied; if they too were skipped, re-check the run. Without a compliance "
                  "side this contrast is inconclusive.", ""]
    else:
        verdict = ("mostly generic" if len(shared_generic) >= len(refusal_only) else "mostly refusal-specific")
        lines += [f"**Verdict: the persistent refusal-opening features are {verdict}.** Of the "
                  f"{len(persistent)} adapter features that drive the refusal opening at >=6 of its "
                  f"{R['n_graphs']} graphs, **{len(shared_generic)} also appear when the adapter COMPLIES** "
                  f"(generic response-start features) and **{len(refusal_only)} appear only on the refusal side** "
                  f"(candidate refusal-specific). Overall top-8 vocabulary overlap (Jaccard) between refusing and "
                  f"complying openings is {jacc:.2f} ({len(inter)} shared of {len(rvocab | cvocab)} total).", "",
                  "This tells us how much of the \"refusal circuit\" localised in `graph_analysis.md` is really "
                  "just the adapter's generic \"I'm the assistant, starting a reply\" machinery (fires for any "
                  "answer) vs. genuinely tied to refusing.", "",
                  "### Persistent refusal features -> generic (also fire when complying)", ""]
        lines += ([f"- {fmt(k)} — top-8 at {R['counts'][k]}/{R['n_graphs']} refusal graphs; also in compliance vocab" for k in shared_generic] or ["- (none)"])
        lines += ["", "### Persistent refusal features -> candidate refusal-specific (absent when complying)", ""]
        lines += ([f"- {fmt(k)} — top-8 at {R['counts'][k]}/{R['n_graphs']} refusal graphs; NOT in compliance vocab" for k in refusal_only] or ["- (none)"])
        lines += [""]

    # Which compliant prompts were kept / skipped.
    lines += ["## Compliant prompts traced", "", f"Refusal side prompts: {', '.join(R['prompts'])}.",
              f"Compliance side prompts kept: {', '.join(C['prompts']) if C['prompts'] else '(none)'}.", ""]

    (HERE / "compare_refusal_compliance.md").write_text("\n".join(lines) + "\n")
    print("wrote", HERE / "compare_refusal_compliance.md")

    # Figure: for each persistent refusal feature, its top-8 frequency on refusal vs compliance side.
    if C["prompts"]:
        import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
        import numpy as np
        feats = persistent
        rfreq = [R["counts"][k] / max(1, R["n_graphs"]) * 100 for k in feats]
        cfreq = [C["counts"].get(k, 0) / max(1, C["n_graphs"]) * 100 for k in feats]
        y = np.arange(len(feats)); h = 0.4
        fig, ax = plt.subplots(figsize=(8, max(3, 0.5 * len(feats))))
        ax.barh(y + h/2, rfreq, h, color="#c53030", label="refusal graphs")
        ax.barh(y - h/2, cfreq, h, color="#2f855a", label="compliance graphs")
        ax.set_yticks(y); ax.set_yticklabels([fmt(k) for k in feats], fontsize=8)
        ax.set_xlabel(f"% of the side's graphs where the feature is top-{TOPK} by |influence|")
        ax.set_title("Persistent refusal-opening features: how often they are top features\nwhen the adapter REFUSES vs. COMPLIES")
        ax.legend(fontsize=8); ax.grid(axis="x", alpha=.3); fig.tight_layout()
        fig.savefig(HERE / "refusal_vs_compliance_overlap.pdf"); fig.savefig(HERE / "refusal_vs_compliance_overlap.png", dpi=150)
        print("wrote", HERE / "refusal_vs_compliance_overlap.pdf")


if __name__ == "__main__":
    main()
