datasets:
  - type: "fineweb"
    datapath: "science-of-finetuning/fineweb-1m-sample"
    max_seq_length: 1000
    length_excession_behavior: "filter"
    weight: 0.5
  - type: "lmsys_chat"
    datapath: "siddharthmb/2026.transcoder-adapters.lmsys-chat-1m-splits"
    max_seq_length: 1000
    length_excession_behavior: "filter"
    weight: 0.5
